name: Auto-assign project
on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/marmot-protocol/projects/5/
          github-token: ${{ secrets.ISSUES_PAT }}

